### ISSUE TITLE
It doesn't seem to work after updating pandas

### ISSUE THREAD

**Issue by Wang-zhechao** [invl/pip-autoremove#36]
Traceback (most recent call last):
  File "d:\program files\python3.7.5\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files\python3.7.5\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Python3.7.5\Scripts\pip-autoremove.exe\__main__.py", line 7, in <module>
  File "d:\program files\python3.7.5\lib\site-packages\pip_autoremove.py", line 106, in main
    autoremove(args, yes=opts.yes)
  File "d:\program files\python3.7.5\lib\site-packages\pip_autoremove.py", line 21, in autoremove
    dead = list_dead(names)
  File "d:\program files\python3.7.5\lib\site-packages\pip_autoremove.py", line 29, in list_dead
    graph = get_graph()
  File "d:\program files\python3.7.5\lib\site-packages\pip_autoremove.py", line 89, in get_graph
    for req in requires(dist):
  File "d:\program files\python3.7.5\lib\site-packages\pkg_resources\__init__.py", line 481, in get_distribution
    dist = get_provider(dist)
  File "d:\program files\python3.7.5\lib\site-packages\pkg_resources\__init__.py", line 357, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "d:\program files\python3.7.5\lib\site-packages\pkg_resources\__init__.py", line 643, in find
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (pandas 1.2.0 (d:\program files\python3.7.5\lib\site-packages), Requirement.parse('pandas<=0.23.4,>=0.20.3'))

**Comment by tresni** [comment]
Most of the VersionConflict errors have been fixed in #16 and on [my branch](https://github.com/tresni/pip-autoremove)

**Comment by tresni** [comment]
Should be addressed by #42 and the new release, please close if that resolves your issue.
