### ISSUE TITLE
Installation fails "The 'testresources' distribution was not found and is required by the application"

### ISSUE THREAD

**Issue by ioogithub** [invl/pip-autoremove#40]
I followed the simple installation instructions found here:

https://pypi.org/project/pip-autoremove/

Here is the result:
```

$ pip-autoremove package
Traceback (most recent call last):
  File "/home/user/.local/bin/pip-autoremove", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.8/site-packages/pip_autoremove.py", line 106, in main
    autoremove(args, yes=opts.yes)
  File "/home/user/.local/lib/python3.8/site-packages/pip_autoremove.py", line 21, in autoremove
    dead = list_dead(names)
  File "/home/user/.local/lib/python3.8/site-packages/pip_autoremove.py", line 29, in list_dead
    graph = get_graph()
  File "/home/user/.local/lib/python3.8/site-packages/pip_autoremove.py", line 89, in get_graph
    for req in requires(dist):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 482, in get_distribution
    dist = get_provider(dist)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 358, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'testresources' distribution was not found and is required by the application
```

The installation did not mention installing any dependencies, shouldn't this just work?

**Comment by ioogithub** [comment]
Please delete this issue. I will find a working solution
