### ISSUE TITLE
ModuleNotFoundError: No module named 'pip_autoremove'

### ISSUE THREAD

**Issue by jzr-supove** [invl/pip-autoremove#50]
Running:

    pip-autoremove Flask

Getting an error:

```
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\Scripts\pip-autoremove.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'pip_autoremove'
```

**Comment by imba-tjd** [comment]
dup of #43
