### ISSUE TITLE
conflict with python 3 version of python-dateutil

### ISSUE THREAD

**Issue by edwardotis** [invl/pip-autoremove#7]
pip-autoremove==0.9.0

It appears to require a python 2 specific version of python-dateutil (1.5)
https://labix.org/python-dateutil#head-b57873b28af6ab8b1c4ae48d522ce0c691abbdf2

I'm on ubuntu 14 lts, python 3.5.1, with 2.5.0 of python-dateutil.
Here is the error.

(myvirtualenv)me@my-vm:~/dev/rational_sales_server$ pip-autoremove --list
Traceback (most recent call last):
  File "/home/me/Envs/myvirtualenv/bin/pip-autoremove", line 11, in <module>
    sys.exit(main())
  File "/home/me/Envs/myvirtualenv/lib/python3.5/site-packages/pip_autoremove.py", line 107, in main
    list_dead(args)
  File "/home/me/Envs/myvirtualenv/lib/python3.5/site-packages/pip_autoremove.py", line 29, in list_dead
    graph = get_graph()
  File "/home/me/Envs/myvirtualenv/lib/python3.5/site-packages/pip_autoremove.py", line 92, in get_graph
    for req in requires(dist):
  File "/home/me/Envs/myvirtualenv/lib/python3.5/site-packages/pkg_resources/**init**.py", line 542, in get_distribution
    dist = get_provider(dist)
  File "/home/me/Envs/myvirtualenv/lib/python3.5/site-packages/pkg_resources/**init**.py", line 422, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/home/me/Envs/myvirtualenv/lib/python3.5/site-packages/pkg_resources/**init**.py", line 702, in find
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (python-dateutil 2.5.0 (/home/me/Envs/myvirtualenv/lib/python3.5/site-packages), Requirement.parse('python-dateutil==1.5'))

**Comment by mgallagher** [comment]
+1. Having this same issue.

**Comment by jegesh** [comment]
+1

**Comment by krerkkiat** [comment]
I have the problem too, but I think its root is in [pkg_resources](https://github.com/pypa/setuptools/blob/ed765324e72e7e6be1f84778eaa7496df0e7a381/pkg_resources/__init__.py#L706). It may be fixed by either handle the pkg_resources.VersionConflict error or edit the pkg_resources itself.

**Comment by qmcree** [comment]
+1. Using Python 2.7.10.

`pkg_resources.VersionConflict: (colorama 0.3.9 (/usr/local/lib/python2.7/site-packages), Requirement.parse('colorama<=0.3.7,>=0.2.5'))`
